<?php

namespace App\Enums;

enum ServiceCategory: string
{
    case LOCAL_CHARGES_POL = 'LOCAL_CHARGES_POL';
    case LOCAL_CHARGES_POD = 'LOCAL_CHARGES_POD';
    case SEAFREIGHT_SURCHARGES = 'SEAFREIGHT_SURCHARGES';
    case ROAD_TRANSPORT_SURCHARGES = 'ROAD_TRANSPORT_SURCHARGES';
    case ADMINISTRATIVE_SURCHARGES = 'ADMINISTRATIVE_SURCHARGES';
    case INSPECTION_SURCHARGES = 'INSPECTION_SURCHARGES';
    case AIRFREIGHT_SURCHARGES = 'AIRFREIGHT_SURCHARGES';
}

